// storybook-publishing-strategies-multiple-frameworks/apps/admin/src/app/app.tsx
import { AdminUiHeader } from '@storybook-publishing-strategies-multiple-frameworks/admin-ui-header';
import { AdminUiFooter } from '@storybook-publishing-strategies-multiple-frameworks/admin-ui-footer';

export function App() {
  return (
    <>
      <AdminUiHeader userName="admin" />
      <AdminUiFooter />
    </>
  );
}

export default App;

// storybook-publishing-strategies-multiple-frameworks/apps/client/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'storybook-publishing-strategies-multiple-frameworks-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'client';
}

<storybook-publishing-strategies-multiple-frameworks-header
  [clientName]="'Jane'"
></storybook-publishing-strategies-multiple-frameworks-header>
<storybook-publishing-strategies-multiple-frameworks-footer></storybook-publishing-strategies-multiple-frameworks-footer>
