// vue-standalone/src/app/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';
</script>

<template>
  <nav>
    <ul>
      <li>
        <RouterLink to="/">Home</RouterLink>
      </li>
      <li>
        <RouterLink to="/products">Products</RouterLink>
      </li>
      <li>
        <RouterLink to="/orders">Orders</RouterLink>
      </li>
    </ul>
  </nav>

  <RouterView />
</template>

// react-app/src/App.tsx
import { Route, Routes } from 'react-router-dom';
import { Products } from 'products';
import { Orders } from 'orders';
import './App.css';

function Home() {
  return <h1>Home</h1>;
}

export function App() {
  return (
    <Routes>
      <Route path="/" element={<Home />}></Route>
      <Route path="/products" element={<Products />}></Route>
      <Route path="/orders" element={<Orders />}></Route>
    </Routes>
  );
}

export default App;
